### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/angular-wp-front-end#1]

**Comment by royboy789** [comment]
@Shelob9 do you think its better to grab ALL posts and have Angular paginate (there is a good directive / plugin for ng-paginate) or just call the API every time?

Should each "page" be unique, or should it just add to the existing page below the last

**Comment by DavidCramer** [comment]
I would load maybe 2-3 pages then background load a few more.

**Comment by royboy789** [comment]
good call, can do that

**Comment by Shelob9** [comment]
I agree with David that getting one or two pages (and local storaging the
JSON response) in advance is smart, but getting all could be a performance
problem.

## 

JoshPress.net http://joshpress.net/
CalderaWP.com http://calderawp.com/
IngotHQ.com
@Josh412 http://twitter.com/Josh412

**Comment by royboy789** [comment]
Getting all isn't really an issue, done it before, but only in limited capacity (A CPT with no more than like 30 posts). I like the idea of reducing HTTP calls, so 1-2 pages at a time should be fine. 

what you thinking as far as UI, whole new list of posts, or just add to existing?

**Comment by Shelob9** [comment]
Regular pagination. Show only current page of posts, that's the sensible default, but make it flexible so its easy to add append later.

Are we local storageing the JSON responses?

**Comment by royboy789** [comment]
wasn't planning on it. could be something we offer later. but this is "simple easy" right? don't want to add complexities in now

**Comment by Shelob9** [comment]
My question is are you going to have to rewrite the whole thing to add localStorage? Part of the point of all of this is it should make it easy to work offline and also if we localStorage JSON it should reduces hits to WordPress and make second page load not be blocked by an HTTP request.

**Comment by royboy789** [comment]
Added in localStorage AND pagination. Pagination triggers new API call, adds to local storage and current scope. need to finish page variable counter. (right now page 2 is hard coded)

**Comment by royboy789** [comment]
Closing for now, please re-open if not satisfied
