### ISSUE TITLE
Category Term Archives

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/angular-wp-front-end#7]

**Comment by royboy789** [comment]
I got this one.

**Comment by royboy789** [comment]
The POST object returns IDs for cats and tags. I think what I may do is on app run, update a localobject with an array of 'id' => 'slug', that way its easy to parse through and find. That way the controller doesn't have to handle both ID and slug, nor will the ID ever be in the URL.

**Comment by royboy789** [comment]
PR #25 closes
